In [1]:
# import pandas dan numpy
import pandas as pd
import numpy as np

print(np.__version__)
print(pd.__version__)

1.19.2
1.1.3

In [3]:
# persiapan data frame
n_rows = 20
n_cols = 10
cols = tuple('ABCDEFGHIJ')

df = pd.DataFrame(np.random.randint(1, 40, size=(n_rows, n_cols)),
                  columns=cols)
df

     A   B   C   D   E   F   G   H   I   J
0   14  35   8  19  10  22   7  24   2   6
1   13  15  34   8   1  12  29  28   1  33
2   10  23  23  16   4  33   1   7  27   7
3   11   3  18  25  23  31  15  23  37   6
4   28  30   4  39  14  16   8   6   3  23
5    2  28  30  35   6  29  27  11  33  15
6   24  29  17  25   9  20  24  36   1   5
7   17  16   8  26  15   7  19   6  18  10
8   35  31  37  19  14  25  37  11  12  29
9   36   9  11   6  12   4  19  32  33  10
10  20  17  23  30   2   1  17  23   3  24
11  22   6   3  39  17   9  18   1  39  29
12  16  12  29  19  30   4  27  16  17  18
13   2  10  26  25  32  36  30  19  23  30
14   2  28   1  11  22  22  30  29  31   6
15  27  34  14  19  12  26  27   1  13  33
16  32  29  36  12  18   1  25  13  16  25
17  21  17  24  15  30  10  13  12  11   5
18  31  16  25   4   8   3  20  36  22  34
19  35  19  32  18  16   3  29   5  13   3